# Generated by Django 5.2.6 on 2025-09-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note'),
        ),
    ]
